// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8Od4JZF1UIS9UOYY8h2a6oa0HtZTJk0',
    appId: '1:805098215445:web:6278b966e2a95ccaa8d61c',
    messagingSenderId: '805098215445',
    projectId: 'chatapp-7c563',
    authDomain: 'chatapp-7c563.firebaseapp.com',
    storageBucket: 'chatapp-7c563.appspot.com',
    measurementId: 'G-E164PLDBKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2r4sF2ww2_H_rjRlnaLsH3Ivnqo1TUkA',
    appId: '1:805098215445:android:1fed157d4d00e63ca8d61c',
    messagingSenderId: '805098215445',
    projectId: 'chatapp-7c563',
    storageBucket: 'chatapp-7c563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9brLS7I6t8ET9_URSh3B3d3pRdPh-6J0',
    appId: '1:805098215445:ios:69cc9fd28995c4aea8d61c',
    messagingSenderId: '805098215445',
    projectId: 'chatapp-7c563',
    storageBucket: 'chatapp-7c563.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9brLS7I6t8ET9_URSh3B3d3pRdPh-6J0',
    appId: '1:805098215445:ios:69cc9fd28995c4aea8d61c',
    messagingSenderId: '805098215445',
    projectId: 'chatapp-7c563',
    storageBucket: 'chatapp-7c563.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ8Od4JZF1UIS9UOYY8h2a6oa0HtZTJk0',
    appId: '1:805098215445:web:1499f7c22771707aa8d61c',
    messagingSenderId: '805098215445',
    projectId: 'chatapp-7c563',
    authDomain: 'chatapp-7c563.firebaseapp.com',
    storageBucket: 'chatapp-7c563.appspot.com',
    measurementId: 'G-CKLK70F25L',
  );
}
